version: "3"
services:
  rag_api:
    container_name: rag-api
    image: adityadockerhub6767/rag_app:1.1.1
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file: rag.env
    volumes:
      - chromadb:/srv/data/chromadb
      - llm-checkpoints:/srv/data/checkpoints
    ports:
      - "2121:8000"
  llama-service:
    container_name: llama-service
    image: adityadockerhub6767/ollama:1.1.1
    restart: always
    volumes:
      - rag-ollama:/root/.ollama
    ports:
      - "11434:11434"
  rag_docker_database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=rag@123
      - POSTGRES_USER=raguser
      - POSTGRES_DB=ragdb
    volumes:
      - rag-postgres:/var/lib/postgresql/data/
    ports:
      - "5439:5432"
  # llm_checkpoints:
  #   image: adityadockerhub6767/llm_checkpoints:1.1.1
  #   container_name: llm_checkpoints
  #   command: "tail -f /dev/null"
  #   restart: unless-stopped
  #   volumes:
  #     - llm-checkpoints:/checkpoints
volumes:
  rag-postgres:
  chromadb:
  llm-checkpoints:
  rag-ollama: